// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct AddCustomAttributesInputHeadersMiddleware: Middleware {
    public let id: String = "AddCustomAttributesInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AddCustomAttributesInput>,
                  next: H) -> Result<OperationOutput<AddCustomAttributesOutput, AddCustomAttributesError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AddCustomAttributesInput>
    public typealias MOutput = OperationOutput<AddCustomAttributesOutput, AddCustomAttributesError>
    public typealias Context = HttpContext
}
