// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct AdminDisableProviderForUserInputHeadersMiddleware: Middleware {
    public let id: String = "AdminDisableProviderForUserInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminDisableProviderForUserInput>,
                  next: H) -> Result<OperationOutput<AdminDisableProviderForUserOutput, AdminDisableProviderForUserError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminDisableProviderForUserInput>
    public typealias MOutput = OperationOutput<AdminDisableProviderForUserOutput, AdminDisableProviderForUserError>
    public typealias Context = HttpContext
}
