// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum AdminCreateUserError {
    case codeDeliveryFailureException(CodeDeliveryFailureException)
    case internalErrorException(InternalErrorException)
    case invalidLambdaResponseException(InvalidLambdaResponseException)
    case invalidParameterException(InvalidParameterException)
    case invalidPasswordException(InvalidPasswordException)
    case invalidSmsRoleAccessPolicyException(InvalidSmsRoleAccessPolicyException)
    case invalidSmsRoleTrustRelationshipException(InvalidSmsRoleTrustRelationshipException)
    case notAuthorizedException(NotAuthorizedException)
    case preconditionNotMetException(PreconditionNotMetException)
    case resourceNotFoundException(ResourceNotFoundException)
    case tooManyRequestsException(TooManyRequestsException)
    case unexpectedLambdaException(UnexpectedLambdaException)
    case unsupportedUserStateException(UnsupportedUserStateException)
    case userLambdaValidationException(UserLambdaValidationException)
    case usernameExistsException(UsernameExistsException)
    case userNotFoundException(UserNotFoundException)
    case unknown(UnknownAWSHttpServiceError)
}
