// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct AdminSetUserSettingsInputHeadersMiddleware: Middleware {
    public let id: String = "AdminSetUserSettingsInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminSetUserSettingsInput>,
                  next: H) -> Result<OperationOutput<AdminSetUserSettingsOutput, AdminSetUserSettingsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminSetUserSettingsInput>
    public typealias MOutput = OperationOutput<AdminSetUserSettingsOutput, AdminSetUserSettingsError>
    public typealias Context = HttpContext
}
