// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct AdminUpdateAuthEventFeedbackInputQueryItemMiddleware: Middleware {
    public let id: String = "AdminUpdateAuthEventFeedbackInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminUpdateAuthEventFeedbackInput>,
                  next: H) -> Result<OperationOutput<AdminUpdateAuthEventFeedbackOutput, AdminUpdateAuthEventFeedbackError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminUpdateAuthEventFeedbackInput>
    public typealias MOutput = OperationOutput<AdminUpdateAuthEventFeedbackOutput, AdminUpdateAuthEventFeedbackError>
    public typealias Context = HttpContext
}
