// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct AdminDeleteUserAttributesInputQueryItemMiddleware: Middleware {
    public let id: String = "AdminDeleteUserAttributesInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminDeleteUserAttributesInput>,
                  next: H) -> Result<OperationOutput<AdminDeleteUserAttributesOutput, AdminDeleteUserAttributesError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminDeleteUserAttributesInput>
    public typealias MOutput = OperationOutput<AdminDeleteUserAttributesOutput, AdminDeleteUserAttributesError>
    public typealias Context = HttpContext
}
