// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension AdminUpdateAuthEventFeedbackInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case eventId = "EventId"
        case feedbackValue = "FeedbackValue"
        case userPoolId = "UserPoolId"
        case username = "Username"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let eventId = eventId {
            try container.encode(eventId, forKey: .eventId)
        }
        if let feedbackValue = feedbackValue {
            try container.encode(feedbackValue.rawValue, forKey: .feedbackValue)
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
        if let username = username {
            try container.encode(username, forKey: .username)
        }
    }
}
