// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension AdminDeleteUserAttributesInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case userAttributeNames = "UserAttributeNames"
        case userPoolId = "UserPoolId"
        case username = "Username"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let userAttributeNames = userAttributeNames {
            var userAttributeNamesContainer = container.nestedUnkeyedContainer(forKey: .userAttributeNames)
            for attributenamelisttype0 in userAttributeNames {
                try userAttributeNamesContainer.encode(attributenamelisttype0)
            }
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
        if let username = username {
            try container.encode(username, forKey: .username)
        }
    }
}
