// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct AdminForgetDeviceInputQueryItemMiddleware: Middleware {
    public let id: String = "AdminForgetDeviceInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminForgetDeviceInput>,
                  next: H) -> Result<OperationOutput<AdminForgetDeviceOutput, AdminForgetDeviceError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminForgetDeviceInput>
    public typealias MOutput = OperationOutput<AdminForgetDeviceOutput, AdminForgetDeviceError>
    public typealias Context = HttpContext
}
