// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct AdminInitiateAuthInputHeadersMiddleware: Middleware {
    public let id: String = "AdminInitiateAuthInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminInitiateAuthInput>,
                  next: H) -> Result<OperationOutput<AdminInitiateAuthOutput, AdminInitiateAuthError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminInitiateAuthInput>
    public typealias MOutput = OperationOutput<AdminInitiateAuthOutput, AdminInitiateAuthError>
    public typealias Context = HttpContext
}
