// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct AdminConfirmSignUpInputQueryItemMiddleware: Middleware {
    public let id: String = "AdminConfirmSignUpInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminConfirmSignUpInput>,
                  next: H) -> Result<OperationOutput<AdminConfirmSignUpOutput, AdminConfirmSignUpError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminConfirmSignUpInput>
    public typealias MOutput = OperationOutput<AdminConfirmSignUpOutput, AdminConfirmSignUpError>
    public typealias Context = HttpContext
}
