// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct AdminCreateUserOutputBody: Equatable {
    public let user: UserType?
}

extension AdminCreateUserOutputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case user = "User"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let userDecoded = try containerValues.decodeIfPresent(UserType.self, forKey: .user)
        user = userDecoded
    }
}
