// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct AdminRespondToAuthChallengeInputQueryItemMiddleware: Middleware {
    public let id: String = "AdminRespondToAuthChallengeInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AdminRespondToAuthChallengeInput>,
                  next: H) -> Result<OperationOutput<AdminRespondToAuthChallengeOutput, AdminRespondToAuthChallengeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AdminRespondToAuthChallengeInput>
    public typealias MOutput = OperationOutput<AdminRespondToAuthChallengeOutput, AdminRespondToAuthChallengeError>
    public typealias Context = HttpContext
}
