// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension AnalyticsConfigurationType: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case applicationArn = "ApplicationArn"
        case applicationId = "ApplicationId"
        case externalId = "ExternalId"
        case roleArn = "RoleArn"
        case userDataShared = "UserDataShared"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let applicationArn = applicationArn {
            try container.encode(applicationArn, forKey: .applicationArn)
        }
        if let applicationId = applicationId {
            try container.encode(applicationId, forKey: .applicationId)
        }
        if let externalId = externalId {
            try container.encode(externalId, forKey: .externalId)
        }
        if let roleArn = roleArn {
            try container.encode(roleArn, forKey: .roleArn)
        }
        if userDataShared != false {
            try container.encode(userDataShared, forKey: .userDataShared)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let applicationIdDecoded = try containerValues.decodeIfPresent(String.self, forKey: .applicationId)
        applicationId = applicationIdDecoded
        let applicationArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .applicationArn)
        applicationArn = applicationArnDecoded
        let roleArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .roleArn)
        roleArn = roleArnDecoded
        let externalIdDecoded = try containerValues.decodeIfPresent(String.self, forKey: .externalId)
        externalId = externalIdDecoded
        let userDataSharedDecoded = try containerValues.decode(Bool.self, forKey: .userDataShared)
        userDataShared = userDataSharedDecoded
    }
}
