// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct AssociateSoftwareTokenInputHeadersMiddleware: Middleware {
    public let id: String = "AssociateSoftwareTokenInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AssociateSoftwareTokenInput>,
                  next: H) -> Result<OperationOutput<AssociateSoftwareTokenOutput, AssociateSoftwareTokenError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AssociateSoftwareTokenInput>
    public typealias MOutput = OperationOutput<AssociateSoftwareTokenOutput, AssociateSoftwareTokenError>
    public typealias Context = HttpContext
}
