// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct ChangePasswordInputQueryItemMiddleware: Middleware {
    public let id: String = "ChangePasswordInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ChangePasswordInput>,
                  next: H) -> Result<OperationOutput<ChangePasswordOutput, ChangePasswordError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ChangePasswordInput>
    public typealias MOutput = OperationOutput<ChangePasswordOutput, ChangePasswordError>
    public typealias Context = HttpContext
}
