// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ChangePasswordInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case accessToken = "AccessToken"
        case previousPassword = "PreviousPassword"
        case proposedPassword = "ProposedPassword"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let accessToken = accessToken {
            try container.encode(accessToken, forKey: .accessToken)
        }
        if let previousPassword = previousPassword {
            try container.encode(previousPassword, forKey: .previousPassword)
        }
        if let proposedPassword = proposedPassword {
            try container.encode(proposedPassword, forKey: .proposedPassword)
        }
    }
}
