// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension CompromisedCredentialsActionsType: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case eventAction = "EventAction"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let eventAction = eventAction {
            try container.encode(eventAction.rawValue, forKey: .eventAction)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let eventActionDecoded = try containerValues.decodeIfPresent(CompromisedCredentialsEventActionType.self, forKey: .eventAction)
        eventAction = eventActionDecoded
    }
}
