// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct CreateResourceServerInputQueryItemMiddleware: Middleware {
    public let id: String = "CreateResourceServerInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateResourceServerInput>,
                  next: H) -> Result<OperationOutput<CreateResourceServerOutput, CreateResourceServerError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateResourceServerInput>
    public typealias MOutput = OperationOutput<CreateResourceServerOutput, CreateResourceServerError>
    public typealias Context = HttpContext
}
