// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CreateUserPoolInputHeadersMiddleware: Middleware {
    public let id: String = "CreateUserPoolInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateUserPoolInput>,
                  next: H) -> Result<OperationOutput<CreateUserPoolOutput, CreateUserPoolError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateUserPoolInput>
    public typealias MOutput = OperationOutput<CreateUserPoolOutput, CreateUserPoolError>
    public typealias Context = HttpContext
}
