// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension CreateGroupInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case description = "Description"
        case groupName = "GroupName"
        case precedence = "Precedence"
        case roleArn = "RoleArn"
        case userPoolId = "UserPoolId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let description = description {
            try container.encode(description, forKey: .description)
        }
        if let groupName = groupName {
            try container.encode(groupName, forKey: .groupName)
        }
        if let precedence = precedence {
            try container.encode(precedence, forKey: .precedence)
        }
        if let roleArn = roleArn {
            try container.encode(roleArn, forKey: .roleArn)
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
    }
}
