// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct CreateResourceServerOutputBody: Equatable {
    public let resourceServer: ResourceServerType?
}

extension CreateResourceServerOutputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case resourceServer = "ResourceServer"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let resourceServerDecoded = try containerValues.decodeIfPresent(ResourceServerType.self, forKey: .resourceServer)
        resourceServer = resourceServerDecoded
    }
}
