// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct CreateUserPoolDomainInputQueryItemMiddleware: Middleware {
    public let id: String = "CreateUserPoolDomainInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateUserPoolDomainInput>,
                  next: H) -> Result<OperationOutput<CreateUserPoolDomainOutput, CreateUserPoolDomainError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateUserPoolDomainInput>
    public typealias MOutput = OperationOutput<CreateUserPoolDomainOutput, CreateUserPoolDomainError>
    public typealias Context = HttpContext
}
