// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension CreateUserImportJobInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case cloudWatchLogsRoleArn = "CloudWatchLogsRoleArn"
        case jobName = "JobName"
        case userPoolId = "UserPoolId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let cloudWatchLogsRoleArn = cloudWatchLogsRoleArn {
            try container.encode(cloudWatchLogsRoleArn, forKey: .cloudWatchLogsRoleArn)
        }
        if let jobName = jobName {
            try container.encode(jobName, forKey: .jobName)
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
    }
}
