// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct DeleteIdentityProviderInputQueryItemMiddleware: Middleware {
    public let id: String = "DeleteIdentityProviderInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DeleteIdentityProviderInput>,
                  next: H) -> Result<OperationOutput<DeleteIdentityProviderOutput, DeleteIdentityProviderError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DeleteIdentityProviderInput>
    public typealias MOutput = OperationOutput<DeleteIdentityProviderOutput, DeleteIdentityProviderError>
    public typealias Context = HttpContext
}
