// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension DeleteUserPoolClientInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case clientId = "ClientId"
        case userPoolId = "UserPoolId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let clientId = clientId {
            try container.encode(clientId, forKey: .clientId)
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
    }
}
