// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension DeleteUserAttributesInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case accessToken = "AccessToken"
        case userAttributeNames = "UserAttributeNames"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let accessToken = accessToken {
            try container.encode(accessToken, forKey: .accessToken)
        }
        if let userAttributeNames = userAttributeNames {
            var userAttributeNamesContainer = container.nestedUnkeyedContainer(forKey: .userAttributeNames)
            for attributenamelisttype0 in userAttributeNames {
                try userAttributeNamesContainer.encode(attributenamelisttype0)
            }
        }
    }
}
