// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct DescribeIdentityProviderInputQueryItemMiddleware: Middleware {
    public let id: String = "DescribeIdentityProviderInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeIdentityProviderInput>,
                  next: H) -> Result<OperationOutput<DescribeIdentityProviderOutput, DescribeIdentityProviderError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeIdentityProviderInput>
    public typealias MOutput = OperationOutput<DescribeIdentityProviderOutput, DescribeIdentityProviderError>
    public typealias Context = HttpContext
}
