// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct DescribeUserPoolDomainInputHeadersMiddleware: Middleware {
    public let id: String = "DescribeUserPoolDomainInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeUserPoolDomainInput>,
                  next: H) -> Result<OperationOutput<DescribeUserPoolDomainOutput, DescribeUserPoolDomainError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeUserPoolDomainInput>
    public typealias MOutput = OperationOutput<DescribeUserPoolDomainOutput, DescribeUserPoolDomainError>
    public typealias Context = HttpContext
}
