// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetIdentityProviderByIdentifierInputHeadersMiddleware: Middleware {
    public let id: String = "GetIdentityProviderByIdentifierInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetIdentityProviderByIdentifierInput>,
                  next: H) -> Result<OperationOutput<GetIdentityProviderByIdentifierOutput, GetIdentityProviderByIdentifierError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetIdentityProviderByIdentifierInput>
    public typealias MOutput = OperationOutput<GetIdentityProviderByIdentifierOutput, GetIdentityProviderByIdentifierError>
    public typealias Context = HttpContext
}
