// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetIdentityProviderByIdentifierOutputBody: Equatable {
    public let identityProvider: IdentityProviderType?
}

extension GetIdentityProviderByIdentifierOutputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case identityProvider = "IdentityProvider"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let identityProviderDecoded = try containerValues.decodeIfPresent(IdentityProviderType.self, forKey: .identityProvider)
        identityProvider = identityProviderDecoded
    }
}
