// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct GetUserAttributeVerificationCodeInputQueryItemMiddleware: Middleware {
    public let id: String = "GetUserAttributeVerificationCodeInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetUserAttributeVerificationCodeInput>,
                  next: H) -> Result<OperationOutput<GetUserAttributeVerificationCodeOutput, GetUserAttributeVerificationCodeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetUserAttributeVerificationCodeInput>
    public typealias MOutput = OperationOutput<GetUserAttributeVerificationCodeOutput, GetUserAttributeVerificationCodeError>
    public typealias Context = HttpContext
}
