// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct GetUserPoolMfaConfigInputQueryItemMiddleware: Middleware {
    public let id: String = "GetUserPoolMfaConfigInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetUserPoolMfaConfigInput>,
                  next: H) -> Result<OperationOutput<GetUserPoolMfaConfigOutput, GetUserPoolMfaConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetUserPoolMfaConfigInput>
    public typealias MOutput = OperationOutput<GetUserPoolMfaConfigOutput, GetUserPoolMfaConfigError>
    public typealias Context = HttpContext
}
