// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct InitiateAuthInputQueryItemMiddleware: Middleware {
    public let id: String = "InitiateAuthInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<InitiateAuthInput>,
                  next: H) -> Result<OperationOutput<InitiateAuthOutput, InitiateAuthError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<InitiateAuthInput>
    public typealias MOutput = OperationOutput<InitiateAuthOutput, InitiateAuthError>
    public typealias Context = HttpContext
}
