// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct ListUsersInGroupInputHeadersMiddleware: Middleware {
    public let id: String = "ListUsersInGroupInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListUsersInGroupInput>,
                  next: H) -> Result<OperationOutput<ListUsersInGroupOutput, ListUsersInGroupError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListUsersInGroupInput>
    public typealias MOutput = OperationOutput<ListUsersInGroupOutput, ListUsersInGroupError>
    public typealias Context = HttpContext
}
