// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct ListUserPoolClientsInputHeadersMiddleware: Middleware {
    public let id: String = "ListUserPoolClientsInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListUserPoolClientsInput>,
                  next: H) -> Result<OperationOutput<ListUserPoolClientsOutput, ListUserPoolClientsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListUserPoolClientsInput>
    public typealias MOutput = OperationOutput<ListUserPoolClientsOutput, ListUserPoolClientsError>
    public typealias Context = HttpContext
}
