// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ListUserImportJobsInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case maxResults = "MaxResults"
        case paginationToken = "PaginationToken"
        case userPoolId = "UserPoolId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if maxResults != 0 {
            try container.encode(maxResults, forKey: .maxResults)
        }
        if let paginationToken = paginationToken {
            try container.encode(paginationToken, forKey: .paginationToken)
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
    }
}
