// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ListUsersInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case attributesToGet = "AttributesToGet"
        case filter = "Filter"
        case limit = "Limit"
        case paginationToken = "PaginationToken"
        case userPoolId = "UserPoolId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let attributesToGet = attributesToGet {
            var attributesToGetContainer = container.nestedUnkeyedContainer(forKey: .attributesToGet)
            for searchedattributenameslisttype0 in attributesToGet {
                try attributesToGetContainer.encode(searchedattributenameslisttype0)
            }
        }
        if let filter = filter {
            try container.encode(filter, forKey: .filter)
        }
        if let limit = limit {
            try container.encode(limit, forKey: .limit)
        }
        if let paginationToken = paginationToken {
            try container.encode(paginationToken, forKey: .paginationToken)
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
    }
}
