// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct ListUserImportJobsInputQueryItemMiddleware: Middleware {
    public let id: String = "ListUserImportJobsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListUserImportJobsInput>,
                  next: H) -> Result<OperationOutput<ListUserImportJobsOutput, ListUserImportJobsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListUserImportJobsInput>
    public typealias MOutput = OperationOutput<ListUserImportJobsOutput, ListUserImportJobsError>
    public typealias Context = HttpContext
}
