// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ListTagsForResourceInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case resourceArn = "ResourceArn"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let resourceArn = resourceArn {
            try container.encode(resourceArn, forKey: .resourceArn)
        }
    }
}
