// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension PasswordPolicyType: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case minimumLength = "MinimumLength"
        case requireLowercase = "RequireLowercase"
        case requireNumbers = "RequireNumbers"
        case requireSymbols = "RequireSymbols"
        case requireUppercase = "RequireUppercase"
        case temporaryPasswordValidityDays = "TemporaryPasswordValidityDays"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if minimumLength != 0 {
            try container.encode(minimumLength, forKey: .minimumLength)
        }
        if requireLowercase != false {
            try container.encode(requireLowercase, forKey: .requireLowercase)
        }
        if requireNumbers != false {
            try container.encode(requireNumbers, forKey: .requireNumbers)
        }
        if requireSymbols != false {
            try container.encode(requireSymbols, forKey: .requireSymbols)
        }
        if requireUppercase != false {
            try container.encode(requireUppercase, forKey: .requireUppercase)
        }
        if temporaryPasswordValidityDays != 0 {
            try container.encode(temporaryPasswordValidityDays, forKey: .temporaryPasswordValidityDays)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let minimumLengthDecoded = try containerValues.decode(Int.self, forKey: .minimumLength)
        minimumLength = minimumLengthDecoded
        let requireUppercaseDecoded = try containerValues.decode(Bool.self, forKey: .requireUppercase)
        requireUppercase = requireUppercaseDecoded
        let requireLowercaseDecoded = try containerValues.decode(Bool.self, forKey: .requireLowercase)
        requireLowercase = requireLowercaseDecoded
        let requireNumbersDecoded = try containerValues.decode(Bool.self, forKey: .requireNumbers)
        requireNumbers = requireNumbersDecoded
        let requireSymbolsDecoded = try containerValues.decode(Bool.self, forKey: .requireSymbols)
        requireSymbols = requireSymbolsDecoded
        let temporaryPasswordValidityDaysDecoded = try containerValues.decode(Int.self, forKey: .temporaryPasswordValidityDays)
        temporaryPasswordValidityDays = temporaryPasswordValidityDaysDecoded
    }
}
