// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct RespondToAuthChallengeInputHeadersMiddleware: Middleware {
    public let id: String = "RespondToAuthChallengeInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<RespondToAuthChallengeInput>,
                  next: H) -> Result<OperationOutput<RespondToAuthChallengeOutput, RespondToAuthChallengeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<RespondToAuthChallengeInput>
    public typealias MOutput = OperationOutput<RespondToAuthChallengeOutput, RespondToAuthChallengeError>
    public typealias Context = HttpContext
}
