// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension RespondToAuthChallengeInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case analyticsMetadata = "AnalyticsMetadata"
        case challengeName = "ChallengeName"
        case challengeResponses = "ChallengeResponses"
        case clientId = "ClientId"
        case clientMetadata = "ClientMetadata"
        case session = "Session"
        case userContextData = "UserContextData"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let analyticsMetadata = analyticsMetadata {
            try container.encode(analyticsMetadata, forKey: .analyticsMetadata)
        }
        if let challengeName = challengeName {
            try container.encode(challengeName.rawValue, forKey: .challengeName)
        }
        if let challengeResponses = challengeResponses {
            var challengeResponsesContainer = container.nestedContainer(keyedBy: Key.self, forKey: .challengeResponses)
            for (dictKey0, challengeresponsestype0) in challengeResponses {
                try challengeResponsesContainer.encode(challengeresponsestype0, forKey: Key(stringValue: dictKey0))
            }
        }
        if let clientId = clientId {
            try container.encode(clientId, forKey: .clientId)
        }
        if let clientMetadata = clientMetadata {
            var clientMetadataContainer = container.nestedContainer(keyedBy: Key.self, forKey: .clientMetadata)
            for (dictKey0, clientmetadatatype0) in clientMetadata {
                try clientMetadataContainer.encode(clientmetadatatype0, forKey: Key(stringValue: dictKey0))
            }
        }
        if let session = session {
            try container.encode(session, forKey: .session)
        }
        if let userContextData = userContextData {
            try container.encode(userContextData, forKey: .userContextData)
        }
    }
}
