// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct SetRiskConfigurationInputQueryItemMiddleware: Middleware {
    public let id: String = "SetRiskConfigurationInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<SetRiskConfigurationInput>,
                  next: H) -> Result<OperationOutput<SetRiskConfigurationOutput, SetRiskConfigurationError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<SetRiskConfigurationInput>
    public typealias MOutput = OperationOutput<SetRiskConfigurationOutput, SetRiskConfigurationError>
    public typealias Context = HttpContext
}
