// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct SetRiskConfigurationOutputBody: Equatable {
    public let riskConfiguration: RiskConfigurationType?
}

extension SetRiskConfigurationOutputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case riskConfiguration = "RiskConfiguration"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let riskConfigurationDecoded = try containerValues.decodeIfPresent(RiskConfigurationType.self, forKey: .riskConfiguration)
        riskConfiguration = riskConfigurationDecoded
    }
}
