// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct SetUserPoolMfaConfigInputQueryItemMiddleware: Middleware {
    public let id: String = "SetUserPoolMfaConfigInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<SetUserPoolMfaConfigInput>,
                  next: H) -> Result<OperationOutput<SetUserPoolMfaConfigOutput, SetUserPoolMfaConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<SetUserPoolMfaConfigInput>
    public typealias MOutput = OperationOutput<SetUserPoolMfaConfigOutput, SetUserPoolMfaConfigError>
    public typealias Context = HttpContext
}
