// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct SetUICustomizationInputQueryItemMiddleware: Middleware {
    public let id: String = "SetUICustomizationInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<SetUICustomizationInput>,
                  next: H) -> Result<OperationOutput<SetUICustomizationOutput, SetUICustomizationError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<SetUICustomizationInput>
    public typealias MOutput = OperationOutput<SetUICustomizationOutput, SetUICustomizationError>
    public typealias Context = HttpContext
}
