// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct SetUserMFAPreferenceInputQueryItemMiddleware: Middleware {
    public let id: String = "SetUserMFAPreferenceInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<SetUserMFAPreferenceInput>,
                  next: H) -> Result<OperationOutput<SetUserMFAPreferenceOutput, SetUserMFAPreferenceError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<SetUserMFAPreferenceInput>
    public typealias MOutput = OperationOutput<SetUserMFAPreferenceOutput, SetUserMFAPreferenceError>
    public typealias Context = HttpContext
}
