// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension SetUserPoolMfaConfigInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case mfaConfiguration = "MfaConfiguration"
        case smsMfaConfiguration = "SmsMfaConfiguration"
        case softwareTokenMfaConfiguration = "SoftwareTokenMfaConfiguration"
        case userPoolId = "UserPoolId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let mfaConfiguration = mfaConfiguration {
            try container.encode(mfaConfiguration.rawValue, forKey: .mfaConfiguration)
        }
        if let smsMfaConfiguration = smsMfaConfiguration {
            try container.encode(smsMfaConfiguration, forKey: .smsMfaConfiguration)
        }
        if let softwareTokenMfaConfiguration = softwareTokenMfaConfiguration {
            try container.encode(softwareTokenMfaConfiguration, forKey: .softwareTokenMfaConfiguration)
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
    }
}
