// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateIdentityProviderInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateIdentityProviderInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateIdentityProviderInput>,
                  next: H) -> Result<OperationOutput<UpdateIdentityProviderOutput, UpdateIdentityProviderError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateIdentityProviderInput>
    public typealias MOutput = OperationOutput<UpdateIdentityProviderOutput, UpdateIdentityProviderError>
    public typealias Context = HttpContext
}
