// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateResourceServerInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case identifier = "Identifier"
        case name = "Name"
        case scopes = "Scopes"
        case userPoolId = "UserPoolId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let identifier = identifier {
            try container.encode(identifier, forKey: .identifier)
        }
        if let name = name {
            try container.encode(name, forKey: .name)
        }
        if let scopes = scopes {
            var scopesContainer = container.nestedUnkeyedContainer(forKey: .scopes)
            for resourceserverscopelisttype0 in scopes {
                try scopesContainer.encode(resourceserverscopelisttype0)
            }
        }
        if let userPoolId = userPoolId {
            try container.encode(userPoolId, forKey: .userPoolId)
        }
    }
}
