// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct VerifyUserAttributeInputQueryItemMiddleware: Middleware {
    public let id: String = "VerifyUserAttributeInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<VerifyUserAttributeInput>,
                  next: H) -> Result<OperationOutput<VerifyUserAttributeOutput, VerifyUserAttributeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<VerifyUserAttributeInput>
    public typealias MOutput = OperationOutput<VerifyUserAttributeOutput, VerifyUserAttributeError>
    public typealias Context = HttpContext
}
