// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct DescribeIdentityInputHeadersMiddleware: Middleware {
    public let id: String = "DescribeIdentityInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeIdentityInput>,
                  next: H) -> Result<OperationOutput<DescribeIdentityOutput, DescribeIdentityError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeIdentityInput>
    public typealias MOutput = OperationOutput<DescribeIdentityOutput, DescribeIdentityError>
    public typealias Context = HttpContext
}
