// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension DescribeIdentityInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case identityId = "IdentityId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let identityId = identityId {
            try container.encode(identityId, forKey: .identityId)
        }
    }
}
