// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetCredentialsForIdentityInputHeadersMiddleware: Middleware {
    public let id: String = "GetCredentialsForIdentityInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetCredentialsForIdentityInput>,
                  next: H) -> Result<OperationOutput<GetCredentialsForIdentityOutput, GetCredentialsForIdentityError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetCredentialsForIdentityInput>
    public typealias MOutput = OperationOutput<GetCredentialsForIdentityOutput, GetCredentialsForIdentityError>
    public typealias Context = HttpContext
}
