// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct GetIdInputQueryItemMiddleware: Middleware {
    public let id: String = "GetIdInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetIdInput>,
                  next: H) -> Result<OperationOutput<GetIdOutput, GetIdError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetIdInput>
    public typealias MOutput = OperationOutput<GetIdOutput, GetIdError>
    public typealias Context = HttpContext
}
