// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct GetOpenIdTokenForDeveloperIdentityInputQueryItemMiddleware: Middleware {
    public let id: String = "GetOpenIdTokenForDeveloperIdentityInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetOpenIdTokenForDeveloperIdentityInput>,
                  next: H) -> Result<OperationOutput<GetOpenIdTokenForDeveloperIdentityOutput, GetOpenIdTokenForDeveloperIdentityError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetOpenIdTokenForDeveloperIdentityInput>
    public typealias MOutput = OperationOutput<GetOpenIdTokenForDeveloperIdentityOutput, GetOpenIdTokenForDeveloperIdentityError>
    public typealias Context = HttpContext
}
