// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct ListIdentityPoolsInputQueryItemMiddleware: Middleware {
    public let id: String = "ListIdentityPoolsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListIdentityPoolsInput>,
                  next: H) -> Result<OperationOutput<ListIdentityPoolsOutput, ListIdentityPoolsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListIdentityPoolsInput>
    public typealias MOutput = OperationOutput<ListIdentityPoolsOutput, ListIdentityPoolsError>
    public typealias Context = HttpContext
}
