// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct UnlinkIdentityInputHeadersMiddleware: Middleware {
    public let id: String = "UnlinkIdentityInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UnlinkIdentityInput>,
                  next: H) -> Result<OperationOutput<UnlinkIdentityOutput, UnlinkIdentityError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UnlinkIdentityInput>
    public typealias MOutput = OperationOutput<UnlinkIdentityOutput, UnlinkIdentityError>
    public typealias Context = HttpContext
}
