// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UntagResourceInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case resourceArn = "ResourceArn"
        case tagKeys = "TagKeys"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let resourceArn = resourceArn {
            try container.encode(resourceArn, forKey: .resourceArn)
        }
        if let tagKeys = tagKeys {
            var tagKeysContainer = container.nestedUnkeyedContainer(forKey: .tagKeys)
            for identitypooltagslisttype0 in tagKeys {
                try tagKeysContainer.encode(identitypooltagslisttype0)
            }
        }
    }
}
