// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateIdentityPoolInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateIdentityPoolInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateIdentityPoolInput>,
                  next: H) -> Result<OperationOutput<UpdateIdentityPoolOutput, UpdateIdentityPoolError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateIdentityPoolInput>
    public typealias MOutput = OperationOutput<UpdateIdentityPoolOutput, UpdateIdentityPoolError>
    public typealias Context = HttpContext
}
