// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension AddLayerVersionPermissionInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case action = "Action"
        case organizationId = "OrganizationId"
        case principal = "Principal"
        case statementId = "StatementId"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let action = action {
            try container.encode(action, forKey: .action)
        }
        if let organizationId = organizationId {
            try container.encode(organizationId, forKey: .organizationId)
        }
        if let principal = principal {
            try container.encode(principal, forKey: .principal)
        }
        if let statementId = statementId {
            try container.encode(statementId, forKey: .statementId)
        }
    }
}
