// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct AddLayerVersionPermissionInputHeadersMiddleware: Middleware {
    public let id: String = "AddLayerVersionPermissionInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<AddLayerVersionPermissionInput>,
                  next: H) -> Result<OperationOutput<AddLayerVersionPermissionOutput, AddLayerVersionPermissionError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<AddLayerVersionPermissionInput>
    public typealias MOutput = OperationOutput<AddLayerVersionPermissionOutput, AddLayerVersionPermissionError>
    public typealias Context = HttpContext
}
