// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct CreateFunctionInputQueryItemMiddleware: Middleware {
    public let id: String = "CreateFunctionInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateFunctionInput>,
                  next: H) -> Result<OperationOutput<CreateFunctionOutput, CreateFunctionError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateFunctionInput>
    public typealias MOutput = OperationOutput<CreateFunctionOutput, CreateFunctionError>
    public typealias Context = HttpContext
}
