// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension CreateAliasInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case description = "Description"
        case functionVersion = "FunctionVersion"
        case name = "Name"
        case routingConfig = "RoutingConfig"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let description = description {
            try container.encode(description, forKey: .description)
        }
        if let functionVersion = functionVersion {
            try container.encode(functionVersion, forKey: .functionVersion)
        }
        if let name = name {
            try container.encode(name, forKey: .name)
        }
        if let routingConfig = routingConfig {
            try container.encode(routingConfig, forKey: .routingConfig)
        }
    }
}
