// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum CreateCodeSigningConfigError {
    case invalidParameterValueException(InvalidParameterValueException)
    case serviceException(ServiceException)
    case unknown(UnknownAWSHttpServiceError)
}
