// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct DeleteEventSourceMappingInputBody: Equatable {
}

extension DeleteEventSourceMappingInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
