// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct DeleteLayerVersionInputBody: Equatable {
}

extension DeleteLayerVersionInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
