// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct DeleteProvisionedConcurrencyConfigInputBody: Equatable {
}

extension DeleteProvisionedConcurrencyConfigInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
