// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct DeleteFunctionCodeSigningConfigInputQueryItemMiddleware: Middleware {
    public let id: String = "DeleteFunctionCodeSigningConfigInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DeleteFunctionCodeSigningConfigInput>,
                  next: H) -> Result<OperationOutput<DeleteFunctionCodeSigningConfigOutput, DeleteFunctionCodeSigningConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DeleteFunctionCodeSigningConfigInput>
    public typealias MOutput = OperationOutput<DeleteFunctionCodeSigningConfigOutput, DeleteFunctionCodeSigningConfigError>
    public typealias Context = HttpContext
}
