// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension FunctionConfiguration: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case codeSha256 = "CodeSha256"
        case codeSize = "CodeSize"
        case deadLetterConfig = "DeadLetterConfig"
        case description = "Description"
        case environment = "Environment"
        case fileSystemConfigs = "FileSystemConfigs"
        case functionArn = "FunctionArn"
        case functionName = "FunctionName"
        case handler = "Handler"
        case imageConfigResponse = "ImageConfigResponse"
        case kMSKeyArn = "KMSKeyArn"
        case lastModified = "LastModified"
        case lastUpdateStatus = "LastUpdateStatus"
        case lastUpdateStatusReason = "LastUpdateStatusReason"
        case lastUpdateStatusReasonCode = "LastUpdateStatusReasonCode"
        case layers = "Layers"
        case masterArn = "MasterArn"
        case memorySize = "MemorySize"
        case packageType = "PackageType"
        case revisionId = "RevisionId"
        case role = "Role"
        case runtime = "Runtime"
        case signingJobArn = "SigningJobArn"
        case signingProfileVersionArn = "SigningProfileVersionArn"
        case state = "State"
        case stateReason = "StateReason"
        case stateReasonCode = "StateReasonCode"
        case timeout = "Timeout"
        case tracingConfig = "TracingConfig"
        case version = "Version"
        case vpcConfig = "VpcConfig"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let codeSha256 = codeSha256 {
            try container.encode(codeSha256, forKey: .codeSha256)
        }
        if codeSize != 0 {
            try container.encode(codeSize, forKey: .codeSize)
        }
        if let deadLetterConfig = deadLetterConfig {
            try container.encode(deadLetterConfig, forKey: .deadLetterConfig)
        }
        if let description = description {
            try container.encode(description, forKey: .description)
        }
        if let environment = environment {
            try container.encode(environment, forKey: .environment)
        }
        if let fileSystemConfigs = fileSystemConfigs {
            var fileSystemConfigsContainer = container.nestedUnkeyedContainer(forKey: .fileSystemConfigs)
            for filesystemconfiglist0 in fileSystemConfigs {
                try fileSystemConfigsContainer.encode(filesystemconfiglist0)
            }
        }
        if let functionArn = functionArn {
            try container.encode(functionArn, forKey: .functionArn)
        }
        if let functionName = functionName {
            try container.encode(functionName, forKey: .functionName)
        }
        if let handler = handler {
            try container.encode(handler, forKey: .handler)
        }
        if let imageConfigResponse = imageConfigResponse {
            try container.encode(imageConfigResponse, forKey: .imageConfigResponse)
        }
        if let kMSKeyArn = kMSKeyArn {
            try container.encode(kMSKeyArn, forKey: .kMSKeyArn)
        }
        if let lastModified = lastModified {
            try container.encode(lastModified, forKey: .lastModified)
        }
        if let lastUpdateStatus = lastUpdateStatus {
            try container.encode(lastUpdateStatus.rawValue, forKey: .lastUpdateStatus)
        }
        if let lastUpdateStatusReason = lastUpdateStatusReason {
            try container.encode(lastUpdateStatusReason, forKey: .lastUpdateStatusReason)
        }
        if let lastUpdateStatusReasonCode = lastUpdateStatusReasonCode {
            try container.encode(lastUpdateStatusReasonCode.rawValue, forKey: .lastUpdateStatusReasonCode)
        }
        if let layers = layers {
            var layersContainer = container.nestedUnkeyedContainer(forKey: .layers)
            for layersreferencelist0 in layers {
                try layersContainer.encode(layersreferencelist0)
            }
        }
        if let masterArn = masterArn {
            try container.encode(masterArn, forKey: .masterArn)
        }
        if let memorySize = memorySize {
            try container.encode(memorySize, forKey: .memorySize)
        }
        if let packageType = packageType {
            try container.encode(packageType.rawValue, forKey: .packageType)
        }
        if let revisionId = revisionId {
            try container.encode(revisionId, forKey: .revisionId)
        }
        if let role = role {
            try container.encode(role, forKey: .role)
        }
        if let runtime = runtime {
            try container.encode(runtime.rawValue, forKey: .runtime)
        }
        if let signingJobArn = signingJobArn {
            try container.encode(signingJobArn, forKey: .signingJobArn)
        }
        if let signingProfileVersionArn = signingProfileVersionArn {
            try container.encode(signingProfileVersionArn, forKey: .signingProfileVersionArn)
        }
        if let state = state {
            try container.encode(state.rawValue, forKey: .state)
        }
        if let stateReason = stateReason {
            try container.encode(stateReason, forKey: .stateReason)
        }
        if let stateReasonCode = stateReasonCode {
            try container.encode(stateReasonCode.rawValue, forKey: .stateReasonCode)
        }
        if let timeout = timeout {
            try container.encode(timeout, forKey: .timeout)
        }
        if let tracingConfig = tracingConfig {
            try container.encode(tracingConfig, forKey: .tracingConfig)
        }
        if let version = version {
            try container.encode(version, forKey: .version)
        }
        if let vpcConfig = vpcConfig {
            try container.encode(vpcConfig, forKey: .vpcConfig)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let functionNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .functionName)
        functionName = functionNameDecoded
        let functionArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .functionArn)
        functionArn = functionArnDecoded
        let runtimeDecoded = try containerValues.decodeIfPresent(Runtime.self, forKey: .runtime)
        runtime = runtimeDecoded
        let roleDecoded = try containerValues.decodeIfPresent(String.self, forKey: .role)
        role = roleDecoded
        let handlerDecoded = try containerValues.decodeIfPresent(String.self, forKey: .handler)
        handler = handlerDecoded
        let codeSizeDecoded = try containerValues.decode(Int.self, forKey: .codeSize)
        codeSize = codeSizeDecoded
        let descriptionDecoded = try containerValues.decodeIfPresent(String.self, forKey: .description)
        description = descriptionDecoded
        let timeoutDecoded = try containerValues.decodeIfPresent(Int.self, forKey: .timeout)
        timeout = timeoutDecoded
        let memorySizeDecoded = try containerValues.decodeIfPresent(Int.self, forKey: .memorySize)
        memorySize = memorySizeDecoded
        let lastModifiedDecoded = try containerValues.decodeIfPresent(String.self, forKey: .lastModified)
        lastModified = lastModifiedDecoded
        let codeSha256Decoded = try containerValues.decodeIfPresent(String.self, forKey: .codeSha256)
        codeSha256 = codeSha256Decoded
        let versionDecoded = try containerValues.decodeIfPresent(String.self, forKey: .version)
        version = versionDecoded
        let vpcConfigDecoded = try containerValues.decodeIfPresent(VpcConfigResponse.self, forKey: .vpcConfig)
        vpcConfig = vpcConfigDecoded
        let deadLetterConfigDecoded = try containerValues.decodeIfPresent(DeadLetterConfig.self, forKey: .deadLetterConfig)
        deadLetterConfig = deadLetterConfigDecoded
        let environmentDecoded = try containerValues.decodeIfPresent(EnvironmentResponse.self, forKey: .environment)
        environment = environmentDecoded
        let kMSKeyArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .kMSKeyArn)
        kMSKeyArn = kMSKeyArnDecoded
        let tracingConfigDecoded = try containerValues.decodeIfPresent(TracingConfigResponse.self, forKey: .tracingConfig)
        tracingConfig = tracingConfigDecoded
        let masterArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .masterArn)
        masterArn = masterArnDecoded
        let revisionIdDecoded = try containerValues.decodeIfPresent(String.self, forKey: .revisionId)
        revisionId = revisionIdDecoded
        let layersContainer = try containerValues.decodeIfPresent([Layer].self, forKey: .layers)
        var layersDecoded0:[Layer]? = nil
        if let layersContainer = layersContainer {
            layersDecoded0 = [Layer]()
            for structure0 in layersContainer {
                layersDecoded0?.append(structure0)
            }
        }
        layers = layersDecoded0
        let stateDecoded = try containerValues.decodeIfPresent(State.self, forKey: .state)
        state = stateDecoded
        let stateReasonDecoded = try containerValues.decodeIfPresent(String.self, forKey: .stateReason)
        stateReason = stateReasonDecoded
        let stateReasonCodeDecoded = try containerValues.decodeIfPresent(StateReasonCode.self, forKey: .stateReasonCode)
        stateReasonCode = stateReasonCodeDecoded
        let lastUpdateStatusDecoded = try containerValues.decodeIfPresent(LastUpdateStatus.self, forKey: .lastUpdateStatus)
        lastUpdateStatus = lastUpdateStatusDecoded
        let lastUpdateStatusReasonDecoded = try containerValues.decodeIfPresent(String.self, forKey: .lastUpdateStatusReason)
        lastUpdateStatusReason = lastUpdateStatusReasonDecoded
        let lastUpdateStatusReasonCodeDecoded = try containerValues.decodeIfPresent(LastUpdateStatusReasonCode.self, forKey: .lastUpdateStatusReasonCode)
        lastUpdateStatusReasonCode = lastUpdateStatusReasonCodeDecoded
        let fileSystemConfigsContainer = try containerValues.decodeIfPresent([FileSystemConfig].self, forKey: .fileSystemConfigs)
        var fileSystemConfigsDecoded0:[FileSystemConfig]? = nil
        if let fileSystemConfigsContainer = fileSystemConfigsContainer {
            fileSystemConfigsDecoded0 = [FileSystemConfig]()
            for structure0 in fileSystemConfigsContainer {
                fileSystemConfigsDecoded0?.append(structure0)
            }
        }
        fileSystemConfigs = fileSystemConfigsDecoded0
        let packageTypeDecoded = try containerValues.decodeIfPresent(PackageType.self, forKey: .packageType)
        packageType = packageTypeDecoded
        let imageConfigResponseDecoded = try containerValues.decodeIfPresent(ImageConfigResponse.self, forKey: .imageConfigResponse)
        imageConfigResponse = imageConfigResponseDecoded
        let signingProfileVersionArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .signingProfileVersionArn)
        signingProfileVersionArn = signingProfileVersionArnDecoded
        let signingJobArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .signingJobArn)
        signingJobArn = signingJobArnDecoded
    }
}
