// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetAccountSettingsInputBody: Equatable {
}

extension GetAccountSettingsInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
