// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct GetAliasInputQueryItemMiddleware: Middleware {
    public let id: String = "GetAliasInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetAliasInput>,
                  next: H) -> Result<OperationOutput<GetAliasOutput, GetAliasError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetAliasInput>
    public typealias MOutput = OperationOutput<GetAliasOutput, GetAliasError>
    public typealias Context = HttpContext
}
