// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetCodeSigningConfigInputBody: Equatable {
}

extension GetCodeSigningConfigInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
