// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct GetCodeSigningConfigInputQueryItemMiddleware: Middleware {
    public let id: String = "GetCodeSigningConfigInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetCodeSigningConfigInput>,
                  next: H) -> Result<OperationOutput<GetCodeSigningConfigOutput, GetCodeSigningConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetCodeSigningConfigInput>
    public typealias MOutput = OperationOutput<GetCodeSigningConfigOutput, GetCodeSigningConfigError>
    public typealias Context = HttpContext
}
