// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetEventSourceMappingInputHeadersMiddleware: Middleware {
    public let id: String = "GetEventSourceMappingInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetEventSourceMappingInput>,
                  next: H) -> Result<OperationOutput<GetEventSourceMappingOutput, GetEventSourceMappingError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetEventSourceMappingInput>
    public typealias MOutput = OperationOutput<GetEventSourceMappingOutput, GetEventSourceMappingError>
    public typealias Context = HttpContext
}
