// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct GetFunctionEventInvokeConfigInputQueryItemMiddleware: Middleware {
    public let id: String = "GetFunctionEventInvokeConfigInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetFunctionEventInvokeConfigInput>,
                  next: H) -> Result<OperationOutput<GetFunctionEventInvokeConfigOutput, GetFunctionEventInvokeConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        if let qualifier = input.operationInput.qualifier {
            let queryItem = URLQueryItem(name: "Qualifier", value: String(qualifier))
            input.builder.withQueryItem(queryItem)
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetFunctionEventInvokeConfigInput>
    public typealias MOutput = OperationOutput<GetFunctionEventInvokeConfigOutput, GetFunctionEventInvokeConfigError>
    public typealias Context = HttpContext
}
