// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetFunctionConcurrencyInputHeadersMiddleware: Middleware {
    public let id: String = "GetFunctionConcurrencyInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetFunctionConcurrencyInput>,
                  next: H) -> Result<OperationOutput<GetFunctionConcurrencyOutput, GetFunctionConcurrencyError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetFunctionConcurrencyInput>
    public typealias MOutput = OperationOutput<GetFunctionConcurrencyOutput, GetFunctionConcurrencyError>
    public typealias Context = HttpContext
}
