// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetFunctionInputBody: Equatable {
}

extension GetFunctionInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
