// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetFunctionConcurrencyInputBody: Equatable {
}

extension GetFunctionConcurrencyInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
