// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetFunctionCodeSigningConfigInputHeadersMiddleware: Middleware {
    public let id: String = "GetFunctionCodeSigningConfigInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetFunctionCodeSigningConfigInput>,
                  next: H) -> Result<OperationOutput<GetFunctionCodeSigningConfigOutput, GetFunctionCodeSigningConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetFunctionCodeSigningConfigInput>
    public typealias MOutput = OperationOutput<GetFunctionCodeSigningConfigOutput, GetFunctionCodeSigningConfigError>
    public typealias Context = HttpContext
}
