// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetFunctionConfigurationInputBody: Equatable {
}

extension GetFunctionConfigurationInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
