// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetLayerVersionInputBody: Equatable {
}

extension GetLayerVersionInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
