// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetLayerVersionByArnInputBody: Equatable {
}

extension GetLayerVersionByArnInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
