// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetLayerVersionPolicyInputBody: Equatable {
}

extension GetLayerVersionPolicyInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
