// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetProvisionedConcurrencyConfigInputBody: Equatable {
}

extension GetProvisionedConcurrencyConfigInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
