// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct GetPolicyInputBody: Equatable {
}

extension GetPolicyInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
