// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ImageConfigResponse: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case error = "Error"
        case imageConfig = "ImageConfig"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let error = error {
            try container.encode(error, forKey: .error)
        }
        if let imageConfig = imageConfig {
            try container.encode(imageConfig, forKey: .imageConfig)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let imageConfigDecoded = try containerValues.decodeIfPresent(ImageConfig.self, forKey: .imageConfig)
        imageConfig = imageConfigDecoded
        let errorDecoded = try containerValues.decodeIfPresent(ImageConfigError.self, forKey: .error)
        error = errorDecoded
    }
}
