// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct InvokeInputBodyMiddleware: Middleware {
    public let id: String = "InvokeInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<InvokeInput>,
                  next: H) -> Result<OperationOutput<InvokeOutput, InvokeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        if let payload = input.operationInput.payload {
            let data = payload
            let body = HttpBody.data(data)
            input.builder.withBody(body)
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<InvokeInput>
    public typealias MOutput = OperationOutput<InvokeOutput, InvokeError>
    public typealias Context = HttpContext
}
