// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension InvokeInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case payload = "Payload"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let payload = payload {
            try container.encode(payload.base64EncodedString(), forKey: .payload)
        }
    }
}
