// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension InvokeAsyncInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case invokeArgs = "InvokeArgs"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let invokeArgs = invokeArgs {
            try container.encode(invokeArgs.base64EncodedString(), forKey: .invokeArgs)
        }
    }
}
