// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct InvokeOutputBody: Equatable {
    public let statusCode: Int
    public let payload: Data?
}

extension InvokeOutputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case payload = "Payload"
        case statusCode = "StatusCode"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let statusCodeDecoded = try containerValues.decode(Int.self, forKey: .statusCode)
        statusCode = statusCodeDecoded
        let payloadDecoded = try containerValues.decodeIfPresent(Data.self, forKey: .payload)
        payload = payloadDecoded
    }
}
