// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension LayerVersionContentOutput: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case codeSha256 = "CodeSha256"
        case codeSize = "CodeSize"
        case location = "Location"
        case signingJobArn = "SigningJobArn"
        case signingProfileVersionArn = "SigningProfileVersionArn"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let codeSha256 = codeSha256 {
            try container.encode(codeSha256, forKey: .codeSha256)
        }
        if codeSize != 0 {
            try container.encode(codeSize, forKey: .codeSize)
        }
        if let location = location {
            try container.encode(location, forKey: .location)
        }
        if let signingJobArn = signingJobArn {
            try container.encode(signingJobArn, forKey: .signingJobArn)
        }
        if let signingProfileVersionArn = signingProfileVersionArn {
            try container.encode(signingProfileVersionArn, forKey: .signingProfileVersionArn)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let locationDecoded = try containerValues.decodeIfPresent(String.self, forKey: .location)
        location = locationDecoded
        let codeSha256Decoded = try containerValues.decodeIfPresent(String.self, forKey: .codeSha256)
        codeSha256 = codeSha256Decoded
        let codeSizeDecoded = try containerValues.decode(Int.self, forKey: .codeSize)
        codeSize = codeSizeDecoded
        let signingProfileVersionArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .signingProfileVersionArn)
        signingProfileVersionArn = signingProfileVersionArnDecoded
        let signingJobArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .signingJobArn)
        signingJobArn = signingJobArnDecoded
    }
}
