// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct ListFunctionsInputHeadersMiddleware: Middleware {
    public let id: String = "ListFunctionsInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListFunctionsInput>,
                  next: H) -> Result<OperationOutput<ListFunctionsOutput, ListFunctionsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListFunctionsInput>
    public typealias MOutput = OperationOutput<ListFunctionsOutput, ListFunctionsError>
    public typealias Context = HttpContext
}
