// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct ListFunctionsByCodeSigningConfigInputBody: Equatable {
}

extension ListFunctionsByCodeSigningConfigInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
