// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct ListProvisionedConcurrencyConfigsInputQueryItemMiddleware: Middleware {
    public let id: String = "ListProvisionedConcurrencyConfigsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListProvisionedConcurrencyConfigsInput>,
                  next: H) -> Result<OperationOutput<ListProvisionedConcurrencyConfigsOutput, ListProvisionedConcurrencyConfigsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        input.builder.withQueryItem(URLQueryItem(name: "List", value: "ALL"))
        if let marker = input.operationInput.marker {
            let queryItem = URLQueryItem(name: "Marker", value: String(marker))
            input.builder.withQueryItem(queryItem)
        }
        if let maxItems = input.operationInput.maxItems {
            let queryItem = URLQueryItem(name: "MaxItems", value: String(maxItems))
            input.builder.withQueryItem(queryItem)
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListProvisionedConcurrencyConfigsInput>
    public typealias MOutput = OperationOutput<ListProvisionedConcurrencyConfigsOutput, ListProvisionedConcurrencyConfigsError>
    public typealias Context = HttpContext
}
