// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct ListProvisionedConcurrencyConfigsInputBody: Equatable {
}

extension ListProvisionedConcurrencyConfigsInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
