// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct ListTagsInputBody: Equatable {
}

extension ListTagsInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
