// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ListEventSourceMappingsInput: Encodable, Reflection {

    public func encode(to encoder: Encoder) throws {
    }
}
