// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct ListAliasesInputBody: Equatable {
}

extension ListAliasesInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
