// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct PublishLayerVersionInputQueryItemMiddleware: Middleware {
    public let id: String = "PublishLayerVersionInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<PublishLayerVersionInput>,
                  next: H) -> Result<OperationOutput<PublishLayerVersionOutput, PublishLayerVersionError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<PublishLayerVersionInput>
    public typealias MOutput = OperationOutput<PublishLayerVersionOutput, PublishLayerVersionError>
    public typealias Context = HttpContext
}
