// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension PutFunctionConcurrencyInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case reservedConcurrentExecutions = "ReservedConcurrentExecutions"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let reservedConcurrentExecutions = reservedConcurrentExecutions {
            try container.encode(reservedConcurrentExecutions, forKey: .reservedConcurrentExecutions)
        }
    }
}
