// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct RemovePermissionInputQueryItemMiddleware: Middleware {
    public let id: String = "RemovePermissionInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<RemovePermissionInput>,
                  next: H) -> Result<OperationOutput<RemovePermissionOutput, RemovePermissionError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        if let qualifier = input.operationInput.qualifier {
            let queryItem = URLQueryItem(name: "Qualifier", value: String(qualifier))
            input.builder.withQueryItem(queryItem)
        }
        if let revisionId = input.operationInput.revisionId {
            let queryItem = URLQueryItem(name: "RevisionId", value: String(revisionId))
            input.builder.withQueryItem(queryItem)
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<RemovePermissionInput>
    public typealias MOutput = OperationOutput<RemovePermissionOutput, RemovePermissionError>
    public typealias Context = HttpContext
}
