// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateFunctionEventInvokeConfigInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case destinationConfig = "DestinationConfig"
        case maximumEventAgeInSeconds = "MaximumEventAgeInSeconds"
        case maximumRetryAttempts = "MaximumRetryAttempts"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let destinationConfig = destinationConfig {
            try container.encode(destinationConfig, forKey: .destinationConfig)
        }
        if let maximumEventAgeInSeconds = maximumEventAgeInSeconds {
            try container.encode(maximumEventAgeInSeconds, forKey: .maximumEventAgeInSeconds)
        }
        if let maximumRetryAttempts = maximumRetryAttempts {
            try container.encode(maximumRetryAttempts, forKey: .maximumRetryAttempts)
        }
    }
}
