// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateEventSourceMappingInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateEventSourceMappingInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateEventSourceMappingInput>,
                  next: H) -> Result<OperationOutput<UpdateEventSourceMappingOutput, UpdateEventSourceMappingError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateEventSourceMappingInput>
    public typealias MOutput = OperationOutput<UpdateEventSourceMappingOutput, UpdateEventSourceMappingError>
    public typealias Context = HttpContext
}
