// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateFunctionCodeInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case dryRun = "DryRun"
        case imageUri = "ImageUri"
        case publish = "Publish"
        case revisionId = "RevisionId"
        case s3Bucket = "S3Bucket"
        case s3Key = "S3Key"
        case s3ObjectVersion = "S3ObjectVersion"
        case zipFile = "ZipFile"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if dryRun != false {
            try container.encode(dryRun, forKey: .dryRun)
        }
        if let imageUri = imageUri {
            try container.encode(imageUri, forKey: .imageUri)
        }
        if publish != false {
            try container.encode(publish, forKey: .publish)
        }
        if let revisionId = revisionId {
            try container.encode(revisionId, forKey: .revisionId)
        }
        if let s3Bucket = s3Bucket {
            try container.encode(s3Bucket, forKey: .s3Bucket)
        }
        if let s3Key = s3Key {
            try container.encode(s3Key, forKey: .s3Key)
        }
        if let s3ObjectVersion = s3ObjectVersion {
            try container.encode(s3ObjectVersion, forKey: .s3ObjectVersion)
        }
        if let zipFile = zipFile {
            try container.encode(zipFile.base64EncodedString(), forKey: .zipFile)
        }
    }
}
