// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct UpdateFunctionEventInvokeConfigInputHeadersMiddleware: Middleware {
    public let id: String = "UpdateFunctionEventInvokeConfigInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateFunctionEventInvokeConfigInput>,
                  next: H) -> Result<OperationOutput<UpdateFunctionEventInvokeConfigOutput, UpdateFunctionEventInvokeConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateFunctionEventInvokeConfigInput>
    public typealias MOutput = OperationOutput<UpdateFunctionEventInvokeConfigOutput, UpdateFunctionEventInvokeConfigError>
    public typealias Context = HttpContext
}
