// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct UpdateCodeSigningConfigInputHeadersMiddleware: Middleware {
    public let id: String = "UpdateCodeSigningConfigInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateCodeSigningConfigInput>,
                  next: H) -> Result<OperationOutput<UpdateCodeSigningConfigOutput, UpdateCodeSigningConfigError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateCodeSigningConfigInput>
    public typealias MOutput = OperationOutput<UpdateCodeSigningConfigOutput, UpdateCodeSigningConfigError>
    public typealias Context = HttpContext
}
