// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct UpdateFunctionCodeInputHeadersMiddleware: Middleware {
    public let id: String = "UpdateFunctionCodeInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateFunctionCodeInput>,
                  next: H) -> Result<OperationOutput<UpdateFunctionCodeOutput, UpdateFunctionCodeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateFunctionCodeInput>
    public typealias MOutput = OperationOutput<UpdateFunctionCodeOutput, UpdateFunctionCodeError>
    public typealias Context = HttpContext
}
