// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ArchivalSummary: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case archivalBackupArn = "ArchivalBackupArn"
        case archivalDateTime = "ArchivalDateTime"
        case archivalReason = "ArchivalReason"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let archivalBackupArn = archivalBackupArn {
            try container.encode(archivalBackupArn, forKey: .archivalBackupArn)
        }
        if let archivalDateTime = archivalDateTime {
            try container.encode(archivalDateTime.timeIntervalSince1970, forKey: .archivalDateTime)
        }
        if let archivalReason = archivalReason {
            try container.encode(archivalReason, forKey: .archivalReason)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let archivalDateTimeDecoded = try containerValues.decodeIfPresent(Date.self, forKey: .archivalDateTime)
        archivalDateTime = archivalDateTimeDecoded
        let archivalReasonDecoded = try containerValues.decodeIfPresent(String.self, forKey: .archivalReason)
        archivalReason = archivalReasonDecoded
        let archivalBackupArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .archivalBackupArn)
        archivalBackupArn = archivalBackupArnDecoded
    }
}
