// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension AttributeValueUpdate: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case action = "Action"
        case value = "Value"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let action = action {
            try container.encode(action.rawValue, forKey: .action)
        }
        if let value = value {
            try container.encode(value, forKey: .value)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let valueDecoded = try containerValues.decodeIfPresent(AttributeValue.self, forKey: .value)
        value = valueDecoded
        let actionDecoded = try containerValues.decodeIfPresent(AttributeAction.self, forKey: .action)
        action = actionDecoded
    }
}
