// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct BatchExecuteStatementInputQueryItemMiddleware: Middleware {
    public let id: String = "BatchExecuteStatementInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<BatchExecuteStatementInput>,
                  next: H) -> Result<OperationOutput<BatchExecuteStatementOutput, BatchExecuteStatementError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<BatchExecuteStatementInput>
    public typealias MOutput = OperationOutput<BatchExecuteStatementOutput, BatchExecuteStatementError>
    public typealias Context = HttpContext
}
