// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct BatchGetItemInputHeadersMiddleware: Middleware {
    public let id: String = "BatchGetItemInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<BatchGetItemInput>,
                  next: H) -> Result<OperationOutput<BatchGetItemOutput, BatchGetItemError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<BatchGetItemInput>
    public typealias MOutput = OperationOutput<BatchGetItemOutput, BatchGetItemError>
    public typealias Context = HttpContext
}
