// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension BatchExecuteStatementInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case statements = "Statements"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let statements = statements {
            var statementsContainer = container.nestedUnkeyedContainer(forKey: .statements)
            for partiqlbatchrequest0 in statements {
                try statementsContainer.encode(partiqlbatchrequest0)
            }
        }
    }
}
