// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct BatchWriteItemInputQueryItemMiddleware: Middleware {
    public let id: String = "BatchWriteItemInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<BatchWriteItemInput>,
                  next: H) -> Result<OperationOutput<BatchWriteItemOutput, BatchWriteItemError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<BatchWriteItemInput>
    public typealias MOutput = OperationOutput<BatchWriteItemOutput, BatchWriteItemError>
    public typealias Context = HttpContext
}
