// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ConsumedCapacity: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case capacityUnits = "CapacityUnits"
        case globalSecondaryIndexes = "GlobalSecondaryIndexes"
        case localSecondaryIndexes = "LocalSecondaryIndexes"
        case readCapacityUnits = "ReadCapacityUnits"
        case table = "Table"
        case tableName = "TableName"
        case writeCapacityUnits = "WriteCapacityUnits"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let capacityUnits = capacityUnits {
            try container.encode(capacityUnits, forKey: .capacityUnits)
        }
        if let globalSecondaryIndexes = globalSecondaryIndexes {
            var globalSecondaryIndexesContainer = container.nestedContainer(keyedBy: Key.self, forKey: .globalSecondaryIndexes)
            for (dictKey0, secondaryindexescapacitymap0) in globalSecondaryIndexes {
                try globalSecondaryIndexesContainer.encode(secondaryindexescapacitymap0, forKey: Key(stringValue: dictKey0))
            }
        }
        if let localSecondaryIndexes = localSecondaryIndexes {
            var localSecondaryIndexesContainer = container.nestedContainer(keyedBy: Key.self, forKey: .localSecondaryIndexes)
            for (dictKey0, secondaryindexescapacitymap0) in localSecondaryIndexes {
                try localSecondaryIndexesContainer.encode(secondaryindexescapacitymap0, forKey: Key(stringValue: dictKey0))
            }
        }
        if let readCapacityUnits = readCapacityUnits {
            try container.encode(readCapacityUnits, forKey: .readCapacityUnits)
        }
        if let table = table {
            try container.encode(table, forKey: .table)
        }
        if let tableName = tableName {
            try container.encode(tableName, forKey: .tableName)
        }
        if let writeCapacityUnits = writeCapacityUnits {
            try container.encode(writeCapacityUnits, forKey: .writeCapacityUnits)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let tableNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .tableName)
        tableName = tableNameDecoded
        let capacityUnitsDecoded = try containerValues.decodeIfPresent(Double.self, forKey: .capacityUnits)
        capacityUnits = capacityUnitsDecoded
        let readCapacityUnitsDecoded = try containerValues.decodeIfPresent(Double.self, forKey: .readCapacityUnits)
        readCapacityUnits = readCapacityUnitsDecoded
        let writeCapacityUnitsDecoded = try containerValues.decodeIfPresent(Double.self, forKey: .writeCapacityUnits)
        writeCapacityUnits = writeCapacityUnitsDecoded
        let tableDecoded = try containerValues.decodeIfPresent(Capacity.self, forKey: .table)
        table = tableDecoded
        let localSecondaryIndexesContainer = try containerValues.decodeIfPresent([String:Capacity].self, forKey: .localSecondaryIndexes)
        var localSecondaryIndexesDecoded0: [String:Capacity]? = nil
        if let localSecondaryIndexesContainer = localSecondaryIndexesContainer {
            localSecondaryIndexesDecoded0 = [String:Capacity]()
            for (key0, capacity0) in localSecondaryIndexesContainer {
                localSecondaryIndexesDecoded0?[key0] = capacity0
            }
        }
        localSecondaryIndexes = localSecondaryIndexesDecoded0
        let globalSecondaryIndexesContainer = try containerValues.decodeIfPresent([String:Capacity].self, forKey: .globalSecondaryIndexes)
        var globalSecondaryIndexesDecoded0: [String:Capacity]? = nil
        if let globalSecondaryIndexesContainer = globalSecondaryIndexesContainer {
            globalSecondaryIndexesDecoded0 = [String:Capacity]()
            for (key0, capacity0) in globalSecondaryIndexesContainer {
                globalSecondaryIndexesDecoded0?[key0] = capacity0
            }
        }
        globalSecondaryIndexes = globalSecondaryIndexesDecoded0
    }
}
