// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ContributorInsightsSummary: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case contributorInsightsStatus = "ContributorInsightsStatus"
        case indexName = "IndexName"
        case tableName = "TableName"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let contributorInsightsStatus = contributorInsightsStatus {
            try container.encode(contributorInsightsStatus.rawValue, forKey: .contributorInsightsStatus)
        }
        if let indexName = indexName {
            try container.encode(indexName, forKey: .indexName)
        }
        if let tableName = tableName {
            try container.encode(tableName, forKey: .tableName)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let tableNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .tableName)
        tableName = tableNameDecoded
        let indexNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .indexName)
        indexName = indexNameDecoded
        let contributorInsightsStatusDecoded = try containerValues.decodeIfPresent(ContributorInsightsStatus.self, forKey: .contributorInsightsStatus)
        contributorInsightsStatus = contributorInsightsStatusDecoded
    }
}
