// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension DeleteBackupInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case backupArn = "BackupArn"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let backupArn = backupArn {
            try container.encode(backupArn, forKey: .backupArn)
        }
    }
}
