// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct DeleteTableInputHeadersMiddleware: Middleware {
    public let id: String = "DeleteTableInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DeleteTableInput>,
                  next: H) -> Result<OperationOutput<DeleteTableOutput, DeleteTableError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DeleteTableInput>
    public typealias MOutput = OperationOutput<DeleteTableOutput, DeleteTableError>
    public typealias Context = HttpContext
}
