// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct DescribeTimeToLiveInputHeadersMiddleware: Middleware {
    public let id: String = "DescribeTimeToLiveInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeTimeToLiveInput>,
                  next: H) -> Result<OperationOutput<DescribeTimeToLiveOutput, DescribeTimeToLiveError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeTimeToLiveInput>
    public typealias MOutput = OperationOutput<DescribeTimeToLiveOutput, DescribeTimeToLiveError>
    public typealias Context = HttpContext
}
