// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct DescribeGlobalTableInputQueryItemMiddleware: Middleware {
    public let id: String = "DescribeGlobalTableInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeGlobalTableInput>,
                  next: H) -> Result<OperationOutput<DescribeGlobalTableOutput, DescribeGlobalTableError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeGlobalTableInput>
    public typealias MOutput = OperationOutput<DescribeGlobalTableOutput, DescribeGlobalTableError>
    public typealias Context = HttpContext
}
