// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension DescribeGlobalTableInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case globalTableName = "GlobalTableName"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let globalTableName = globalTableName {
            try container.encode(globalTableName, forKey: .globalTableName)
        }
    }
}
