// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct DescribeExportInputBody: Equatable {
    public let exportArn: String?
}

extension DescribeExportInputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case exportArn = "ExportArn"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let exportArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .exportArn)
        exportArn = exportArnDecoded
    }
}
