// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct DescribeContinuousBackupsInputQueryItemMiddleware: Middleware {
    public let id: String = "DescribeContinuousBackupsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeContinuousBackupsInput>,
                  next: H) -> Result<OperationOutput<DescribeContinuousBackupsOutput, DescribeContinuousBackupsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeContinuousBackupsInput>
    public typealias MOutput = OperationOutput<DescribeContinuousBackupsOutput, DescribeContinuousBackupsError>
    public typealias Context = HttpContext
}
