// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct DescribeGlobalTableInputBody: Equatable {
    public let globalTableName: String?
}

extension DescribeGlobalTableInputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case globalTableName = "GlobalTableName"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let globalTableNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .globalTableName)
        globalTableName = globalTableNameDecoded
    }
}
