// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct DescribeTableInputQueryItemMiddleware: Middleware {
    public let id: String = "DescribeTableInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeTableInput>,
                  next: H) -> Result<OperationOutput<DescribeTableOutput, DescribeTableError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeTableInput>
    public typealias MOutput = OperationOutput<DescribeTableOutput, DescribeTableError>
    public typealias Context = HttpContext
}
