// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct DescribeExportInputHeadersMiddleware: Middleware {
    public let id: String = "DescribeExportInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeExportInput>,
                  next: H) -> Result<OperationOutput<DescribeExportOutput, DescribeExportError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeExportInput>
    public typealias MOutput = OperationOutput<DescribeExportOutput, DescribeExportError>
    public typealias Context = HttpContext
}
