// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct DescribeLimitsInputBody: Equatable {
}

extension DescribeLimitsInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
