// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct DescribeGlobalTableSettingsInputQueryItemMiddleware: Middleware {
    public let id: String = "DescribeGlobalTableSettingsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeGlobalTableSettingsInput>,
                  next: H) -> Result<OperationOutput<DescribeGlobalTableSettingsOutput, DescribeGlobalTableSettingsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeGlobalTableSettingsInput>
    public typealias MOutput = OperationOutput<DescribeGlobalTableSettingsOutput, DescribeGlobalTableSettingsError>
    public typealias Context = HttpContext
}
