// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct ExecuteStatementInputQueryItemMiddleware: Middleware {
    public let id: String = "ExecuteStatementInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ExecuteStatementInput>,
                  next: H) -> Result<OperationOutput<ExecuteStatementOutput, ExecuteStatementError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ExecuteStatementInput>
    public typealias MOutput = OperationOutput<ExecuteStatementOutput, ExecuteStatementError>
    public typealias Context = HttpContext
}
