// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct ExportTableToPointInTimeOutputBody: Equatable {
    public let exportDescription: ExportDescription?
}

extension ExportTableToPointInTimeOutputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case exportDescription = "ExportDescription"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let exportDescriptionDecoded = try containerValues.decodeIfPresent(ExportDescription.self, forKey: .exportDescription)
        exportDescription = exportDescriptionDecoded
    }
}
