// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct ExportTableToPointInTimeInputHeadersMiddleware: Middleware {
    public let id: String = "ExportTableToPointInTimeInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ExportTableToPointInTimeInput>,
                  next: H) -> Result<OperationOutput<ExportTableToPointInTimeOutput, ExportTableToPointInTimeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ExportTableToPointInTimeInput>
    public typealias MOutput = OperationOutput<ExportTableToPointInTimeOutput, ExportTableToPointInTimeError>
    public typealias Context = HttpContext
}
