// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetItemInputHeadersMiddleware: Middleware {
    public let id: String = "GetItemInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetItemInput>,
                  next: H) -> Result<OperationOutput<GetItemOutput, GetItemError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetItemInput>
    public typealias MOutput = OperationOutput<GetItemOutput, GetItemError>
    public typealias Context = HttpContext
}
