// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct ListContributorInsightsInputQueryItemMiddleware: Middleware {
    public let id: String = "ListContributorInsightsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListContributorInsightsInput>,
                  next: H) -> Result<OperationOutput<ListContributorInsightsOutput, ListContributorInsightsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListContributorInsightsInput>
    public typealias MOutput = OperationOutput<ListContributorInsightsOutput, ListContributorInsightsError>
    public typealias Context = HttpContext
}
