// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ListTablesInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case exclusiveStartTableName = "ExclusiveStartTableName"
        case limit = "Limit"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let exclusiveStartTableName = exclusiveStartTableName {
            try container.encode(exclusiveStartTableName, forKey: .exclusiveStartTableName)
        }
        if let limit = limit {
            try container.encode(limit, forKey: .limit)
        }
    }
}
