// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ListExportsInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case maxResults = "MaxResults"
        case nextToken = "NextToken"
        case tableArn = "TableArn"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let maxResults = maxResults {
            try container.encode(maxResults, forKey: .maxResults)
        }
        if let nextToken = nextToken {
            try container.encode(nextToken, forKey: .nextToken)
        }
        if let tableArn = tableArn {
            try container.encode(tableArn, forKey: .tableArn)
        }
    }
}
