// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ListGlobalTablesInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case exclusiveStartGlobalTableName = "ExclusiveStartGlobalTableName"
        case limit = "Limit"
        case regionName = "RegionName"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let exclusiveStartGlobalTableName = exclusiveStartGlobalTableName {
            try container.encode(exclusiveStartGlobalTableName, forKey: .exclusiveStartGlobalTableName)
        }
        if let limit = limit {
            try container.encode(limit, forKey: .limit)
        }
        if let regionName = regionName {
            try container.encode(regionName, forKey: .regionName)
        }
    }
}
