// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct ListTagsOfResourceInputQueryItemMiddleware: Middleware {
    public let id: String = "ListTagsOfResourceInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<ListTagsOfResourceInput>,
                  next: H) -> Result<OperationOutput<ListTagsOfResourceOutput, ListTagsOfResourceError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<ListTagsOfResourceInput>
    public typealias MOutput = OperationOutput<ListTagsOfResourceOutput, ListTagsOfResourceError>
    public typealias Context = HttpContext
}
