// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension PointInTimeRecoverySpecification: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case pointInTimeRecoveryEnabled = "PointInTimeRecoveryEnabled"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let pointInTimeRecoveryEnabled = pointInTimeRecoveryEnabled {
            try container.encode(pointInTimeRecoveryEnabled, forKey: .pointInTimeRecoveryEnabled)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let pointInTimeRecoveryEnabledDecoded = try containerValues.decodeIfPresent(Bool.self, forKey: .pointInTimeRecoveryEnabled)
        pointInTimeRecoveryEnabled = pointInTimeRecoveryEnabledDecoded
    }
}
