// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ReplicaGlobalSecondaryIndexAutoScalingDescription: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case indexName = "IndexName"
        case indexStatus = "IndexStatus"
        case provisionedReadCapacityAutoScalingSettings = "ProvisionedReadCapacityAutoScalingSettings"
        case provisionedWriteCapacityAutoScalingSettings = "ProvisionedWriteCapacityAutoScalingSettings"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let indexName = indexName {
            try container.encode(indexName, forKey: .indexName)
        }
        if let indexStatus = indexStatus {
            try container.encode(indexStatus.rawValue, forKey: .indexStatus)
        }
        if let provisionedReadCapacityAutoScalingSettings = provisionedReadCapacityAutoScalingSettings {
            try container.encode(provisionedReadCapacityAutoScalingSettings, forKey: .provisionedReadCapacityAutoScalingSettings)
        }
        if let provisionedWriteCapacityAutoScalingSettings = provisionedWriteCapacityAutoScalingSettings {
            try container.encode(provisionedWriteCapacityAutoScalingSettings, forKey: .provisionedWriteCapacityAutoScalingSettings)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let indexNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .indexName)
        indexName = indexNameDecoded
        let indexStatusDecoded = try containerValues.decodeIfPresent(IndexStatus.self, forKey: .indexStatus)
        indexStatus = indexStatusDecoded
        let provisionedReadCapacityAutoScalingSettingsDecoded = try containerValues.decodeIfPresent(AutoScalingSettingsDescription.self, forKey: .provisionedReadCapacityAutoScalingSettings)
        provisionedReadCapacityAutoScalingSettings = provisionedReadCapacityAutoScalingSettingsDecoded
        let provisionedWriteCapacityAutoScalingSettingsDecoded = try containerValues.decodeIfPresent(AutoScalingSettingsDescription.self, forKey: .provisionedWriteCapacityAutoScalingSettings)
        provisionedWriteCapacityAutoScalingSettings = provisionedWriteCapacityAutoScalingSettingsDecoded
    }
}
