// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension ReplicaGlobalSecondaryIndexAutoScalingUpdate: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case indexName = "IndexName"
        case provisionedReadCapacityAutoScalingUpdate = "ProvisionedReadCapacityAutoScalingUpdate"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let indexName = indexName {
            try container.encode(indexName, forKey: .indexName)
        }
        if let provisionedReadCapacityAutoScalingUpdate = provisionedReadCapacityAutoScalingUpdate {
            try container.encode(provisionedReadCapacityAutoScalingUpdate, forKey: .provisionedReadCapacityAutoScalingUpdate)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let indexNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .indexName)
        indexName = indexNameDecoded
        let provisionedReadCapacityAutoScalingUpdateDecoded = try containerValues.decodeIfPresent(AutoScalingSettingsUpdate.self, forKey: .provisionedReadCapacityAutoScalingUpdate)
        provisionedReadCapacityAutoScalingUpdate = provisionedReadCapacityAutoScalingUpdateDecoded
    }
}
