// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct RestoreTableToPointInTimeInputQueryItemMiddleware: Middleware {
    public let id: String = "RestoreTableToPointInTimeInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<RestoreTableToPointInTimeInput>,
                  next: H) -> Result<OperationOutput<RestoreTableToPointInTimeOutput, RestoreTableToPointInTimeError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<RestoreTableToPointInTimeInput>
    public typealias MOutput = OperationOutput<RestoreTableToPointInTimeOutput, RestoreTableToPointInTimeError>
    public typealias Context = HttpContext
}
