// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension RestoreTableToPointInTimeInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case billingModeOverride = "BillingModeOverride"
        case globalSecondaryIndexOverride = "GlobalSecondaryIndexOverride"
        case localSecondaryIndexOverride = "LocalSecondaryIndexOverride"
        case provisionedThroughputOverride = "ProvisionedThroughputOverride"
        case restoreDateTime = "RestoreDateTime"
        case sSESpecificationOverride = "SSESpecificationOverride"
        case sourceTableArn = "SourceTableArn"
        case sourceTableName = "SourceTableName"
        case targetTableName = "TargetTableName"
        case useLatestRestorableTime = "UseLatestRestorableTime"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let billingModeOverride = billingModeOverride {
            try container.encode(billingModeOverride.rawValue, forKey: .billingModeOverride)
        }
        if let globalSecondaryIndexOverride = globalSecondaryIndexOverride {
            var globalSecondaryIndexOverrideContainer = container.nestedUnkeyedContainer(forKey: .globalSecondaryIndexOverride)
            for globalsecondaryindexlist0 in globalSecondaryIndexOverride {
                try globalSecondaryIndexOverrideContainer.encode(globalsecondaryindexlist0)
            }
        }
        if let localSecondaryIndexOverride = localSecondaryIndexOverride {
            var localSecondaryIndexOverrideContainer = container.nestedUnkeyedContainer(forKey: .localSecondaryIndexOverride)
            for localsecondaryindexlist0 in localSecondaryIndexOverride {
                try localSecondaryIndexOverrideContainer.encode(localsecondaryindexlist0)
            }
        }
        if let provisionedThroughputOverride = provisionedThroughputOverride {
            try container.encode(provisionedThroughputOverride, forKey: .provisionedThroughputOverride)
        }
        if let restoreDateTime = restoreDateTime {
            try container.encode(restoreDateTime.timeIntervalSince1970, forKey: .restoreDateTime)
        }
        if let sSESpecificationOverride = sSESpecificationOverride {
            try container.encode(sSESpecificationOverride, forKey: .sSESpecificationOverride)
        }
        if let sourceTableArn = sourceTableArn {
            try container.encode(sourceTableArn, forKey: .sourceTableArn)
        }
        if let sourceTableName = sourceTableName {
            try container.encode(sourceTableName, forKey: .sourceTableName)
        }
        if let targetTableName = targetTableName {
            try container.encode(targetTableName, forKey: .targetTableName)
        }
        if let useLatestRestorableTime = useLatestRestorableTime {
            try container.encode(useLatestRestorableTime, forKey: .useLatestRestorableTime)
        }
    }
}
