// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension StreamSpecification: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case streamEnabled = "StreamEnabled"
        case streamViewType = "StreamViewType"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let streamEnabled = streamEnabled {
            try container.encode(streamEnabled, forKey: .streamEnabled)
        }
        if let streamViewType = streamViewType {
            try container.encode(streamViewType.rawValue, forKey: .streamViewType)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let streamEnabledDecoded = try containerValues.decodeIfPresent(Bool.self, forKey: .streamEnabled)
        streamEnabled = streamEnabledDecoded
        let streamViewTypeDecoded = try containerValues.decodeIfPresent(StreamViewType.self, forKey: .streamViewType)
        streamViewType = streamViewTypeDecoded
    }
}
