// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension TransactGetItem: Codable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case `get` = "Get"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let `get` = `get` {
            try container.encode(`get`, forKey: .`get`)
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let getDecoded = try containerValues.decodeIfPresent(Get.self, forKey: .get)
        get = getDecoded
    }
}
