// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateContributorInsightsInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case contributorInsightsAction = "ContributorInsightsAction"
        case indexName = "IndexName"
        case tableName = "TableName"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let contributorInsightsAction = contributorInsightsAction {
            try container.encode(contributorInsightsAction.rawValue, forKey: .contributorInsightsAction)
        }
        if let indexName = indexName {
            try container.encode(indexName, forKey: .indexName)
        }
        if let tableName = tableName {
            try container.encode(tableName, forKey: .tableName)
        }
    }
}
