// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateTimeToLiveInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case tableName = "TableName"
        case timeToLiveSpecification = "TimeToLiveSpecification"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let tableName = tableName {
            try container.encode(tableName, forKey: .tableName)
        }
        if let timeToLiveSpecification = timeToLiveSpecification {
            try container.encode(timeToLiveSpecification, forKey: .timeToLiveSpecification)
        }
    }
}
