// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateGlobalTableInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case globalTableName = "GlobalTableName"
        case replicaUpdates = "ReplicaUpdates"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let globalTableName = globalTableName {
            try container.encode(globalTableName, forKey: .globalTableName)
        }
        if let replicaUpdates = replicaUpdates {
            var replicaUpdatesContainer = container.nestedUnkeyedContainer(forKey: .replicaUpdates)
            for replicaupdatelist0 in replicaUpdates {
                try replicaUpdatesContainer.encode(replicaupdatelist0)
            }
        }
    }
}
