// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateContinuousBackupsInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case pointInTimeRecoverySpecification = "PointInTimeRecoverySpecification"
        case tableName = "TableName"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let pointInTimeRecoverySpecification = pointInTimeRecoverySpecification {
            try container.encode(pointInTimeRecoverySpecification, forKey: .pointInTimeRecoverySpecification)
        }
        if let tableName = tableName {
            try container.encode(tableName, forKey: .tableName)
        }
    }
}
