// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateItemInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateItemInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateItemInput>,
                  next: H) -> Result<OperationOutput<UpdateItemOutput, UpdateItemError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateItemInput>
    public typealias MOutput = OperationOutput<UpdateItemOutput, UpdateItemError>
    public typealias Context = HttpContext
}
