// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateGlobalTableSettingsInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case globalTableBillingMode = "GlobalTableBillingMode"
        case globalTableGlobalSecondaryIndexSettingsUpdate = "GlobalTableGlobalSecondaryIndexSettingsUpdate"
        case globalTableName = "GlobalTableName"
        case globalTableProvisionedWriteCapacityAutoScalingSettingsUpdate = "GlobalTableProvisionedWriteCapacityAutoScalingSettingsUpdate"
        case globalTableProvisionedWriteCapacityUnits = "GlobalTableProvisionedWriteCapacityUnits"
        case replicaSettingsUpdate = "ReplicaSettingsUpdate"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let globalTableBillingMode = globalTableBillingMode {
            try container.encode(globalTableBillingMode.rawValue, forKey: .globalTableBillingMode)
        }
        if let globalTableGlobalSecondaryIndexSettingsUpdate = globalTableGlobalSecondaryIndexSettingsUpdate {
            var globalTableGlobalSecondaryIndexSettingsUpdateContainer = container.nestedUnkeyedContainer(forKey: .globalTableGlobalSecondaryIndexSettingsUpdate)
            for globaltableglobalsecondaryindexsettingsupdatelist0 in globalTableGlobalSecondaryIndexSettingsUpdate {
                try globalTableGlobalSecondaryIndexSettingsUpdateContainer.encode(globaltableglobalsecondaryindexsettingsupdatelist0)
            }
        }
        if let globalTableName = globalTableName {
            try container.encode(globalTableName, forKey: .globalTableName)
        }
        if let globalTableProvisionedWriteCapacityAutoScalingSettingsUpdate = globalTableProvisionedWriteCapacityAutoScalingSettingsUpdate {
            try container.encode(globalTableProvisionedWriteCapacityAutoScalingSettingsUpdate, forKey: .globalTableProvisionedWriteCapacityAutoScalingSettingsUpdate)
        }
        if let globalTableProvisionedWriteCapacityUnits = globalTableProvisionedWriteCapacityUnits {
            try container.encode(globalTableProvisionedWriteCapacityUnits, forKey: .globalTableProvisionedWriteCapacityUnits)
        }
        if let replicaSettingsUpdate = replicaSettingsUpdate {
            var replicaSettingsUpdateContainer = container.nestedUnkeyedContainer(forKey: .replicaSettingsUpdate)
            for replicasettingsupdatelist0 in replicaSettingsUpdate {
                try replicaSettingsUpdateContainer.encode(replicasettingsupdatelist0)
            }
        }
    }
}
