// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateContributorInsightsInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateContributorInsightsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateContributorInsightsInput>,
                  next: H) -> Result<OperationOutput<UpdateContributorInsightsOutput, UpdateContributorInsightsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateContributorInsightsInput>
    public typealias MOutput = OperationOutput<UpdateContributorInsightsOutput, UpdateContributorInsightsError>
    public typealias Context = HttpContext
}
