// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateTimeToLiveInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateTimeToLiveInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateTimeToLiveInput>,
                  next: H) -> Result<OperationOutput<UpdateTimeToLiveOutput, UpdateTimeToLiveError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateTimeToLiveInput>
    public typealias MOutput = OperationOutput<UpdateTimeToLiveOutput, UpdateTimeToLiveError>
    public typealias Context = HttpContext
}
