// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateTableReplicaAutoScalingInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateTableReplicaAutoScalingInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateTableReplicaAutoScalingInput>,
                  next: H) -> Result<OperationOutput<UpdateTableReplicaAutoScalingOutput, UpdateTableReplicaAutoScalingError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateTableReplicaAutoScalingInput>
    public typealias MOutput = OperationOutput<UpdateTableReplicaAutoScalingOutput, UpdateTableReplicaAutoScalingError>
    public typealias Context = HttpContext
}
