// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

struct UpdateContinuousBackupsOutputBody: Equatable {
    public let continuousBackupsDescription: ContinuousBackupsDescription?
}

extension UpdateContinuousBackupsOutputBody: Decodable {
    private enum CodingKeys: String, CodingKey {
        case continuousBackupsDescription = "ContinuousBackupsDescription"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let continuousBackupsDescriptionDecoded = try containerValues.decodeIfPresent(ContinuousBackupsDescription.self, forKey: .continuousBackupsDescription)
        continuousBackupsDescription = continuousBackupsDescriptionDecoded
    }
}
