// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

extension UpdateTableInput: Encodable, Reflection {
    private enum CodingKeys: String, CodingKey {
        case attributeDefinitions = "AttributeDefinitions"
        case billingMode = "BillingMode"
        case globalSecondaryIndexUpdates = "GlobalSecondaryIndexUpdates"
        case provisionedThroughput = "ProvisionedThroughput"
        case replicaUpdates = "ReplicaUpdates"
        case sSESpecification = "SSESpecification"
        case streamSpecification = "StreamSpecification"
        case tableName = "TableName"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let attributeDefinitions = attributeDefinitions {
            var attributeDefinitionsContainer = container.nestedUnkeyedContainer(forKey: .attributeDefinitions)
            for attributedefinitions0 in attributeDefinitions {
                try attributeDefinitionsContainer.encode(attributedefinitions0)
            }
        }
        if let billingMode = billingMode {
            try container.encode(billingMode.rawValue, forKey: .billingMode)
        }
        if let globalSecondaryIndexUpdates = globalSecondaryIndexUpdates {
            var globalSecondaryIndexUpdatesContainer = container.nestedUnkeyedContainer(forKey: .globalSecondaryIndexUpdates)
            for globalsecondaryindexupdatelist0 in globalSecondaryIndexUpdates {
                try globalSecondaryIndexUpdatesContainer.encode(globalsecondaryindexupdatelist0)
            }
        }
        if let provisionedThroughput = provisionedThroughput {
            try container.encode(provisionedThroughput, forKey: .provisionedThroughput)
        }
        if let replicaUpdates = replicaUpdates {
            var replicaUpdatesContainer = container.nestedUnkeyedContainer(forKey: .replicaUpdates)
            for replicationgroupupdatelist0 in replicaUpdates {
                try replicaUpdatesContainer.encode(replicationgroupupdatelist0)
            }
        }
        if let sSESpecification = sSESpecification {
            try container.encode(sSESpecification, forKey: .sSESpecification)
        }
        if let streamSpecification = streamSpecification {
            try container.encode(streamSpecification, forKey: .streamSpecification)
        }
        if let tableName = tableName {
            try container.encode(tableName, forKey: .tableName)
        }
    }
}
