// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation

public struct UpdateContinuousBackupsInputQueryItemMiddleware: Middleware {
    public let id: String = "UpdateContinuousBackupsInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateContinuousBackupsInput>,
                  next: H) -> Result<OperationOutput<UpdateContinuousBackupsOutput, UpdateContinuousBackupsError>, Error>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateContinuousBackupsInput>
    public typealias MOutput = OperationOutput<UpdateContinuousBackupsOutput, UpdateContinuousBackupsError>
    public typealias Context = HttpContext
}
